
package introsde.assignment3.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://soap.assignment3.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @param p
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(name = "create", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreatePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/People/createPersonRequest", output = "http://soap.assignment3.introsde/People/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "p", targetNamespace = "")
        Person p);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Preference>
     */
    @WebMethod
    @WebResult(name = "readPreferences", targetNamespace = "")
    @RequestWrapper(localName = "readPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPreferences")
    @ResponseWrapper(localName = "readPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/readPreferencesRequest", output = "http://soap.assignment3.introsde/People/readPreferencesResponse")
    public List<Preference> readPreferences();

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.DeletePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/People/deletePersonRequest", output = "http://soap.assignment3.introsde/People/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Person>
     */
    @WebMethod
    @WebResult(name = "personList", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonListResponse")
    @Action(input = "http://soap.assignment3.introsde/People/readPersonListRequest", output = "http://soap.assignment3.introsde/People/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param id
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonResponse")
    @Action(input = "http://soap.assignment3.introsde/People/readPersonRequest", output = "http://soap.assignment3.introsde/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param p
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/People/updatePersonRequest", output = "http://soap.assignment3.introsde/People/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "p", targetNamespace = "")
        Person p);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.SavePersonPreferences")
    @ResponseWrapper(localName = "savePersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.SavePersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/savePersonPreferencesRequest", output = "http://soap.assignment3.introsde/People/savePersonPreferencesResponse")
    public void savePersonPreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Preference arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Preference>
     */
    @WebMethod
    @WebResult(name = "getBestPersonPreference", targetNamespace = "")
    @RequestWrapper(localName = "getBestPersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetBestPersonPreference")
    @ResponseWrapper(localName = "getBestPersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetBestPersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/People/getBestPersonPreferenceRequest", output = "http://soap.assignment3.introsde/People/getBestPersonPreferenceResponse")
    public List<Preference> getBestPersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Preference
     */
    @WebMethod
    @WebResult(name = "readPreferences", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferences2", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferences2")
    @ResponseWrapper(localName = "readPersonPreferences2Response", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferences2Response")
    @Action(input = "http://soap.assignment3.introsde/People/readPersonPreferences2Request", output = "http://soap.assignment3.introsde/People/readPersonPreferences2Response")
    public Preference readPersonPreferences2(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updatePersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonPreferences")
    @ResponseWrapper(localName = "updatePersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/updatePersonPreferencesRequest", output = "http://soap.assignment3.introsde/People/updatePersonPreferencesResponse")
    public void updatePersonPreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Preference arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Preference
     */
    @WebMethod
    @WebResult(name = "evaluatePersonPreferences", targetNamespace = "")
    @RequestWrapper(localName = "evaluatePersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.EvaluatePersonPreferences")
    @ResponseWrapper(localName = "evaluatePersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.EvaluatePersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/People/evaluatePersonPreferencesRequest", output = "http://soap.assignment3.introsde/People/evaluatePersonPreferencesResponse")
    public Preference evaluatePersonPreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Preference arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Preference>
     */
    @WebMethod
    @WebResult(name = "readPersonPreferences", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferences1", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferences1")
    @ResponseWrapper(localName = "readPersonPreferences1Response", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferences1Response")
    @Action(input = "http://soap.assignment3.introsde/People/readPersonPreferences1Request", output = "http://soap.assignment3.introsde/People/readPersonPreferences1Response")
    public List<Preference> readPersonPreferences1(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
