
package introsde.assignment3.soap.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://ws.soap.assignment3.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonListResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonListRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param personIn
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/updatePersonRequest", output = "http://ws.soap.assignment3.introsde/People/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "personIn", targetNamespace = "")
        Person personIn);

    /**
     * 
     * @param personIn
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.CreatePersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/createPersonRequest", output = "http://ws.soap.assignment3.introsde/People/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "personIn", targetNamespace = "")
        Person personIn);

    /**
     * 
     * @param personId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.DeletePersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/deletePersonRequest", output = "http://ws.soap.assignment3.introsde/People/deletePersonResponse")
    public String deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param atName
     * @param personId
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferences1", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferences1")
    @ResponseWrapper(localName = "readPersonPreferences1Response", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferences1Response")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonPreferences1Request", output = "http://ws.soap.assignment3.introsde/People/readPersonPreferences1Response")
    public List<Activity> readPersonPreferences1(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "atName", targetNamespace = "")
        String atName);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "readPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPreferences")
    @ResponseWrapper(localName = "readPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/readPreferencesResponse")
    public List<Activity> readPreferences();

    /**
     * 
     * @param personId
     * @param idActivity
     * @return
     *     returns introsde.assignment3.soap.ws.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferences2", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferences2")
    @ResponseWrapper(localName = "readPersonPreferences2Response", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferences2Response")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonPreferences2Request", output = "http://ws.soap.assignment3.introsde/People/readPersonPreferences2Response")
    public Activity readPersonPreferences2(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "idActivity", targetNamespace = "")
        int idActivity);

    /**
     * 
     * @param activity
     * @param personId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "savePersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.SavePersonPreferences")
    @ResponseWrapper(localName = "savePersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.SavePersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/savePersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/savePersonPreferencesResponse")
    public String savePersonPreferences(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity);

    /**
     * 
     * @param personId
     * @param activityIn
     * @return
     *     returns introsde.assignment3.soap.ws.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "")
    @RequestWrapper(localName = "updatePersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonPreferences")
    @ResponseWrapper(localName = "updatePersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/updatePersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/updatePersonPreferencesResponse")
    public Activity updatePersonPreferences(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "activityIn", targetNamespace = "")
        Activity activityIn);

    /**
     * 
     * @param rating
     * @param personId
     * @param activityIn
     * @return
     *     returns introsde.assignment3.soap.ws.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "")
    @RequestWrapper(localName = "evaluatePersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.EvaluatePersonPreferences")
    @ResponseWrapper(localName = "evaluatePersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.EvaluatePersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/evaluatePersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/evaluatePersonPreferencesResponse")
    public Activity evaluatePersonPreferences(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "activityIn", targetNamespace = "")
        Activity activityIn,
        @WebParam(name = "rating", targetNamespace = "")
        int rating);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "getBestPersonPreference", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.GetBestPersonPreference")
    @ResponseWrapper(localName = "getBestPersonPreferenceResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.GetBestPersonPreferenceResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/getBestPersonPreferenceRequest", output = "http://ws.soap.assignment3.introsde/People/getBestPersonPreferenceResponse")
    public List<Activity> getBestPersonPreference(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "initDB", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.InitDB")
    @ResponseWrapper(localName = "initDBResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.InitDBResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/initDBRequest", output = "http://ws.soap.assignment3.introsde/People/initDBResponse")
    public List<Person> initDB();

}
